### ISSUE TITLE
cannot load exported torchscript model with pytorch_mobile (in flutter) 

### ISSUE THREAD

**Issue by sadegh16** [pytorch/android-demo-app#116]
1-using D2GO, I exported "faster_rcnn_fbnetv3a_dsmask_C4" pretrsined model with the code provided here : https://github.com/pytorch/android-demo-app/blob/master/D2Go/create_d2go.py
with torch==1.8.0 torchvision==0.9.0 torchaudio=0.8.0.
So finally got "d2go.pt" file.

Then in flutter I tried to load d2go.pt model with package pytorch_mobile. But when I reach the line
PyTorchMobile.loadModel('assets/models/d2go.pt');
I get the following errors in my Log:
E/PyTorchMobile(17944): assets/models/d2go.pt is not a proper model
E/PyTorchMobile(17944): com.facebook.jni.CppException:
E/PyTorchMobile(17944): Unknown builtin op: torchvision::nms.
E/PyTorchMobile(17944): Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
E/PyTorchMobile(17944): :
E/PyTorchMobile(17944): File "/content/drive/MyDrive/detection/env/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 36
E/PyTorchMobile(17944): """
E/PyTorchMobile(17944): _assert_has_ops()
E/PyTorchMobile(17944): return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
E/PyTorchMobile(17944): ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
E/PyTorchMobile(17944): Serialized File "code/torch/torchvision/ops/boxes.py", line 26
E/PyTorchMobile(17944): _8 = torch.torchvision.extension._assert_has_ops
E/PyTorchMobile(17944): _9 = _8()
E/PyTorchMobile(17944): _10 = ops.torchvision.nms(boxes, scores, iou_threshold)
E/PyTorchMobile(17944): ~~~~~~~~~~~~~~~~~~~ <--- HERE
E/PyTorchMobile(17944): return _10
E/PyTorchMobile(17944):
E/PyTorchMobile(17944): at org.pytorch.NativePeer.initHybrid(Native Method)
E/PyTorchMobile(17944): at org.pytorch.NativePeer.(NativePeer.java:24)
E/PyTorchMobile(17944): at org.pytorch.Module.load(Module.java:23)
E/PyTorchMobile(17944): at io.fynn.pytorch_mobile.PyTorchMobilePlugin.onMethodCall(PyTorchMobilePlugin.java:46)
E/PyTorchMobile(17944): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/PyTorchMobile(17944): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/PyTorchMobile(17944): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/PyTorchMobile(17944): at android.os.MessageQueue.nativePollOnce(Native Method)
E/PyTorchMobile(17944): at android.os.MessageQueue.next(MessageQueue.java:325)
E/PyTorchMobile(17944): at android.os.Looper.loop(Looper.java:142)
E/PyTorchMobile(17944): at android.app.ActivityThread.main(ActivityThread.java:6944)
E/PyTorchMobile(17944): at java.lang.reflect.Method.invoke(Native Method)
E/PyTorchMobile(17944): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/PyTorchMobile(17944): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Expected behavior:
loading the model.

Is there anyone who knows what is happening?!

**Comment by Morpheushealer73** [comment]
Hi, have you solved this
