### ISSUE TITLE
(Object Detection) Loading asset: Unsupported value kind: Object

### ISSUE THREAD

**Issue by GabrielOAzevedo** [pytorch/android-demo-app#132]
Hello,

I was trying to run the Object Detection example app but it keeps crashing on startup with the following stack trace:

`    --------- beginning of crash
2021-04-27 08:12:06.781 18126-18126/org.pytorch.demo.objectdetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 18126
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: java.lang.RuntimeException: Unsupported value kind: Object
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.RuntimeException: Unsupported value kind: Object
        at org.pytorch.NativePeer.initHybridAndroidAsset(Native Method)
        at org.pytorch.NativePeer.<init>(NativePeer.java:27)
        at org.pytorch.PyTorchAndroid.loadModuleFromAsset(PyTorchAndroid.java:31)
        at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:165)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) `
        
I am running it on my physical device, haven't tried running on the emulator as it doesn't work correctly on my machine. I ran a quick debug session to find the causes but I couldn't find a culprit.

Crashes on line 165 which is:

`mModule = PyTorchAndroid.loadModuleFromAsset(getAssets(), "yolov5s.torchscript.pt");`

**Comment by ANewAnonymous** [comment]
> Hello,
> 
> I was trying to run the Object Detection example app but it keeps crashing on startup with the following stack trace:
> 
> ` --------- beginning of crash 2021-04-27 08:12:06.781 18126-18126/org.pytorch.demo.objectdetection E/AndroidRuntime: FATAL EXCEPTION: main Process: org.pytorch.demo.objectdetection, PID: 18126 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: java.lang.RuntimeException: Unsupported value kind: Object at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8506) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) Caused by: java.lang.RuntimeException: Unsupported value kind: Object at org.pytorch.NativePeer.initHybridAndroidAsset(Native Method) at org.pytorch.NativePeer.<init>(NativePeer.java:27) at org.pytorch.PyTorchAndroid.loadModuleFromAsset(PyTorchAndroid.java:31) at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:165) at android.app.Activity.performCreate(Activity.java:8198) at android.app.Activity.performCreate(Activity.java:8182) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)  at android.os.Handler.dispatchMessage(Handler.java:106)  at android.os.Looper.loop(Looper.java:246)  at android.app.ActivityThread.main(ActivityThread.java:8506)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) `
> 
> I am running it on my physical device, haven't tried running on the emulator as it doesn't work correctly on my machine. I ran a quick debug session to find the causes but I couldn't find a culprit.
> 
> Crashes on line 165 which is:
> 
> `mModule = PyTorchAndroid.loadModuleFromAsset(getAssets(), "yolov5s.torchscript.pt");`

I also encountered the same problem as yours. This error occurred after I converted my model and put it back into the Android project to run it. I look forward to a solution.

**Comment by GabrielOAzevedo** [comment]
Solved by upgrading app level build.gradle pytorch dependencies to 1.8.0.

Before:
`implementation 'org.pytorch:pytorch_android:1.7.0'
  implementation 'org.pytorch:pytorch_android_torchvision:1.7.0'`
  
After:
`
implementation 'org.pytorch:pytorch_android:1.8.0'
implementation 'org.pytorch:pytorch_android_torchvision:1.8.0'
`

**Comment by AlexBlack2202** [comment]
> Solved by upgrading app level build.gradle pytorch dependencies to 1.8.0.
> 
> Before:
> `implementation 'org.pytorch:pytorch_android:1.7.0' implementation 'org.pytorch:pytorch_android_torchvision:1.7.0'`
> 
> After:
> `implementation 'org.pytorch:pytorch_android:1.8.0' implementation 'org.pytorch:pytorch_android_torchvision:1.8.0'`

this work for me. Thank
