### ISSUE TITLE
NativeApp Error in compute.pt generation

### ISSUE THREAD

**Issue by H1Gdev** [pytorch/android-demo-app#134]
# Execution

```sh
cd NativeApp
python make_warp_perspective_pt.py
```
# Error

```
1.6.0
Using /home/<USER>/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/<USER>/.cache/torch_extensions/warp_perspective/build.ninja...
Building extension module warp_perspective...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=warp_perspective -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/include -isystem /home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/include/TH -isystem /home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/include/THC -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/<USER>/.cache/torch_extensions/warp_perspective/main.cpp -o main.o 
[2/2] c++ main.o -shared -lopencv_core -lopencv_imgproc -L/home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o warp_perspective.so
Loading extension module warp_perspective...
Traceback (most recent call last):
  File "make_warp_perspective_pt.py", line 36, in <module>
    verbose=True,
  File "/home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1124, in load_inline
    keep_intermediates=keep_intermediates)
  File "/home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1190, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1540, in _import_module_from_library
    torch.ops.load_library(path)
  File "/home/<USER>/works/PyTorch/temp/venv3.6/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/<USER>/.cache/torch_extensions/warp_perspective/warp_perspective.so: undefined symbol: _ZN2cv3MatC1Ev
```

- use `Python 3.6`
- use `PyTorch 1.6.0`
- install `libopencv-dev`

Symbol of OpenCV seems to be missing.
Do I need any other settings ?

**Comment by H1Gdev** [comment]
This is collision issue between OpenCV2 and 3...
