### ISSUE TITLE
Android app crashing after launch

### ISSUE THREAD

**Issue by myasser63** [pytorch/android-demo-app#182]
hello, I am using the same method of `export.py` to convert my custom `yolov5s` and loaded my model to the pytorch android demo app (Github Link: https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection). the app builds with no error. however, the app launches and immediately crashes every time. 

the error message here:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 9957
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()
    Exception raised from valid at ../caffe2/serialize/inline_container.cc:157 (most recent call first):
    (no backtrace available)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()
    Exception raised from valid at ../caffe2/serialize/inline_container.cc:157 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.initHybrid(Native Method)
        at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:23)
        at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:29)
        at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:184)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
        	... 11 more
W/System: A resource failed to call close. 
I/Process: Sending signal. PID: 9957 SIG: 9

_Originally posted by @myasser63 in https://github.com/pytorch/android-demo-app/issues/102#issuecomment-909279475_

**Comment by myasser63** [comment]
@jeffxtang could you assist me with this issue

**Comment by jeffxtang** [comment]
> @jeffxtang could you assist me with this issue

Does the app run fine with the [model](https://drive.google.com/u/1/uc?id=1_MF7NVi9Csm1lizoSCp1wCtUUUpuhwet&export=download)?

**Comment by myasser63** [comment]
No, it has the same issue

**Comment by myasser63** [comment]
@jeffxtang yes it runs fine

I have tried different `export.py` versions and still can't run on the demo app even when I use the default `yolov5s.pt` weights

**Comment by jeffxtang** [comment]
> @jeffxtang yes it runs fine
> 
> I have tried different `export.py` versions and still can't run on the demo app even when I use the default `yolov5s.pt` weights

I just tried the repo and the app with the downloaded model in AS 4.2 and it works for me, in both emulator and Pixel 3 phone. 

What version of AS, phone or emulator are you using? Did you get the same error when using the downloaded `yolov5s.torchscript.ptl` file? Or what error message? You shouldn't used the `yolov5s.pt` file as this app has been updated to use the lite interpreter model `yolov5s.torchscript.ptl` (see the download like above).

Finally, does your app build.gradle file have:
```
    implementation 'org.pytorch:pytorch_android_lite:1.9.0'
    implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'
```
?

**Comment by myasser63** [comment]
> > @jeffxtang yes it runs fine
> > I have tried different `export.py` versions and still can't run on the demo app even when I use the default `yolov5s.pt` weights
> 
> I just tried the repo and the app with the downloaded model in AS 4.2 and it works for me, in both emulator and Pixel 3 phone.
> 
> What version of AS, phone or emulator are you using? Did you get the same error when using the downloaded `yolov5s.torchscript.ptl` file? Or what error message? You shouldn't used the `yolov5s.pt` file as this app has been updated to use the lite interpreter model `yolov5s.torchscript.ptl` (see the download like above).
> 
> Finally, does your app build.gradle file have:
> 
> ```
>     implementation 'org.pytorch:pytorch_android_lite:1.9.0'
>     implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'
> ```
> 
> ?

**Comment by myasser63** [comment]
I am using AS 4.2 with both emulator and on Oneplus 7t pro phone. both got the same above error message.

When I used ` yolov5s.torchscript.ptl` I didn't get errors and app runs fine.
I used `yolov5s.pt` with `export.py` to see if he problem is with my trained weights and I got the same error message with my trained custom model yolov5s.

My build.gradle includes 
 ```
   implementation 'org.pytorch:pytorch_android_lite:1.9.0'
    implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'

```

**Comment by myasser63** [comment]
> I am using AS 4.2 with both emulator and on Oneplus 7t pro phone. both got the same above error message.
> 
> When I used ` yolov5s.torchscript.ptl` I didn't get errors and app runs fine.
> I used `yolov5s.pt` with `export.py` to see if he problem is with my trained weights and I got the same error message with my trained custom model yolov5s.
> 
> My build.gradle includes
> 
> ```
>   implementation 'org.pytorch:pytorch_android_lite:1.9.0'
>    implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'
> ```



> > @jeffxtang yes it runs fine
> > I have tried different `export.py` versions and still can't run on the demo app even when I use the default `yolov5s.pt` weights
> 
> I just tried the repo and the app with the downloaded model in AS 4.2 and it works for me, in both emulator and Pixel 3 phone.
> 
> What version of AS, phone or emulator are you using? Did you get the same error when using the downloaded `yolov5s.torchscript.ptl` file? Or what error message? You shouldn't used the `yolov5s.pt` file as this app has been updated to use the lite interpreter model `yolov5s.torchscript.ptl` (see the download like above).
> 
> Finally, does your app build.gradle file have:
> 
> ```
>     implementation 'org.pytorch:pytorch_android_lite:1.9.0'
>     implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'
> ```
> 
> ?

I am using AS 4.2 with both emulator and on Oneplus 7t pro phone. both got the same above error message.

When I used `yolov5s.torchscript.ptl` I didn't get errors and app runs fine.
I used `yolov5s.pt` with `export.py` to see if he problem is with my trained weights or not and I got the same error message with my trained custom model yolov5s.

My build.gradle includes

```
  implementation 'org.pytorch:pytorch_android_lite:1.9.0'
   implementation 'org.pytorch:pytorch_android_torchvision:1.9.0'
```

**Comment by jeffxtang** [comment]
Did you get the latest https://github.com/jeffxtang/yolov5/blob/master/models/export.py? It has code updated 2 days ago that generates the `yolov5s.torchscript.ptl`. Non-lite version of model such as `yolov5s.pt` won't work with app built with `implementation 'org.pytorch:pytorch_android_lite:1.9.0'`.

**Comment by myasser63** [comment]
> Did you get the latest https://github.com/jeffxtang/yolov5/blob/master/models/export.py? It has code updated 2 days ago that generates the `yolov5s.torchscript.ptl`. Non-lite version of model such as `yolov5s.pt` won't work with app built with `implementation 'org.pytorch:pytorch_android_lite:1.9.0'`.

 

@jeffxtang Can you please explain bit more about " non-lite version of model such as yolov5s.pt won't work with app built with `implementation 'org.pytorch:pytorch_android_lite:1.9.0` " what lite model I can use on my own dataset?

So after I train my custom yolov5s on my own dataset, it wont work with app built with `implementation 'org.pytorch:pytorch_android_lite:1.9.0`  after exporting as `best.torchscript.ptl`?

**Comment by jeffxtang** [comment]
https://pytorch.org/tutorials/recipes/mobile_interpreter.html has more explanation. 

In the latest export.py, there're:
```
        jit_fn = opt.weights.replace('.pt', '.torchscript.pt')
        lite_fn = opt.weights.replace('.pt', '.torchscript.ptl')
```
Only the second model file works with `implementation 'org.pytorch:pytorch_android_lite:1.9.0`

**Comment by myasser63** [comment]
> https://pytorch.org/tutorials/recipes/mobile_interpreter.html has more explanation.
> 
> In the latest export.py, there're:
> 
> ```
>         jit_fn = opt.weights.replace('.pt', '.torchscript.pt')
>         lite_fn = opt.weights.replace('.pt', '.torchscript.ptl')
> ```
> 
> Only the second model file works with `implementation 'org.pytorch:pytorch_android_lite:1.9.0`

I have tried the latest version of `export.py` with my custom model trained on one class `--image_size 640` and `--batch_size 16`. i get this different error when try to use live mode or detect buttons.


The error message:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 3542
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=7
        at org.pytorch.demo.objectdetection.ResultView.onDraw(ResultView.java:63)
        at android.view.View.draw(View.java:22528)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at com.android.internal.policy.DecorView.draw(DecorView.java:848)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4417)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1049)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/Process: Sending signal. PID: 3542 SIG: 9

**Comment by jeffxtang** [comment]
This [thread](https://github.com/pytorch/android-demo-app/issues/102#issuecomment-790034948) may help although the error there was different.

**Comment by myasser63** [comment]
> This [thread](https://github.com/pytorch/android-demo-app/issues/102#issuecomment-790034948) may help although the error there was different.
@jeffxtang
The app is working fine but there is no detection results either through live or detection buttons

**Comment by ainia123** [comment]
You can use the latest export.py to export .ptl

**Comment by myasser63** [comment]
> You can use the latest export.py to `export.py`
I used the latest `export.py `version

**Comment by jeffxtang** [comment]
Thanks and there's a [PR](https://github.com/pytorch/android-demo-app/pull/185) just created with a new section Transfer Learning covering the details of doing the custom data training, using the latest export.py, and making Android code change.

**Comment by myasser63** [comment]
@jeffxtang thanks for your assistance. the app is working fine now. I will close this issue

**Comment by HripsimeS** [comment]
@jeffxtang Hello. I tried your https://github.com/jeffxtang/yolov5/blob/master/models/export.py file to convert my **pt**  model to **torchscript.ptl** but I am getting the following error. 

File export.py, line 34, in <module>
model = attempt_load(opt.weights, map_location=torch.device('cpu'))  # load FP32 model
TypeError: attempt_load() got an unexpected keyword argument 'map_location'

Do you know what is going wrong with the process and how I can fix it? Thanks a lot in advance!
