### ISSUE TITLE
Getting CppException: Lite Interpreter version number does not match

### ISSUE THREAD

**Issue by stefan-falk** [pytorch/android-demo-app#206]
Running the Android app after generating the model throws the following error:

```none
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: org.pytorch.demo.speechrecognition, PID: 10645
    com.facebook.jni.CppException: Lite Interpreter verson number does not match. The model version must be between 3 and 5But the model version is 7 ()
    Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:320 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.initHybrid(Native Method)
        at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:23)
        at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:29)
        at org.pytorch.demo.speechrecognition.MainActivity.recognize(MainActivity.java:197)
        at org.pytorch.demo.speechrecognition.MainActivity.run(MainActivity.java:183)
        at java.lang.Thread.run(Thread.java:923)
```

Is this a dependency issue?

**Comment by Treshank** [comment]
Duplicate of #202. I think

**Comment by stefan-falk** [comment]
@Treshank indeed! Thanks for linking!
