### ISSUE TITLE
My app is not working It giving me bug error Please Help me this my final year project

### ISSUE THREAD

**Issue by Joe-KI333** [pytorch/android-demo-app#211]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: Lite Interpreter verson number does not match. The model version must be between 3 and 5But the model version is 7 ()
Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:320 (most recent call first):
(no backtrace available)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2976)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
Caused by: com.facebook.jni.CppException: Lite Interpreter verson number does not match. The model version must be between 3 and 5But the model version is 7 ()
Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:320 (most recent call first):
(no backtrace available)
	at org.pytorch.LiteNativePeer.initHybrid(Native Method)
	at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:23)
	at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:29)
	at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:184)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)

**Comment by SOURAB-BAPPA** [comment]
same problem any solution??
