### ISSUE TITLE
 app crashed with my customized segment model

### ISSUE THREAD

**Issue by gneworld** [pytorch/android-demo-app#26]
run PyTorchDemoApp app with my customized segment model, app crashed with following error, thanks for any suggestions

2019-10-30 16:54:00.469 13290-13342/org.pytorch.demo E/PyTorchDemo: Error during image analysis
    java.lang.IllegalStateException: Expected IValue type 2, actual type 7
        at org.pytorch.IValue.preconditionType(IValue.java:307)
        at org.pytorch.IValue.toTensor(IValue.java:240)
        at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:181)
        at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:31)
        at org.pytorch.demo.vision.AbstractCameraXActivity.lambda$setupCameraX$2$AbstractCameraXActivity(AbstractCameraXActivity.java:90)
        at org.pytorch.demo.vision.-$$Lambda$AbstractCameraXActivity$t0OjLr-l_M0-_0_dUqVE4yqEYnE.analyze(lambda)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:57)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:135)
        at android.os.Handler.handleCallback(Handler.java:751)

**Comment by gneworld** [comment]
@IvanKobzarev  Your help is appreciated

**Comment by Defolters** [comment]
@gneworld It's because forward() on your model returns Tuple, not tensor.

**Comment by IvanKobzarev** [comment]
Sorry for my delay with response.
Just FYI: You may also ask on https://discuss.pytorch.org/c/mobile or in https://github.com/pytorch/pytorch/issues as more pytorch people will see it.

Yes, the previous answer is right
IValue is 'tagged union' where type code is stored `IValue.mTypeCode`
Model call returned IValue with `mTypeCode==7 (TYPE_CODE_TUPLE)` while you tried to call `IValue.toTensor()`
For tuple we should call: `IValue.toTuple()`

**Comment by SungmanHong** [comment]
@Defolters  thanks for your help

in the ORG code of `Tensor outputs = model.forward(inputs).toTensor();`

I changed it `Tensor outputs = model.forward(inputs).toTuple();`

but how can i change the tensor? there seems no tuple type in android studio...
