### ISSUE TITLE
Pytorch lite version problem with error in android app

### ISSUE THREAD

**Issue by Jagan3534** [pytorch/android-demo-app#275]
for our custom .ptl model
we got error in this Ivalue

```
Tensor outputTensor = module.forward(IValue.from(inputTensor)).toTensor();
float[] scores = outputTensor.getDataAsFloatArray();
```
and
```
IValue inputs = IValue.from(tensor);
IValue[] outputs = module.forward(inputs).toTuple();
```
i tried in both ways

i got the error like this 
```
java.lang.IllegalStateException: Expected IValue type Tuple, actual type TensorList
at org.pytorch.IValue.preconditionType(IValue.java:332)
at org.pytorch.IValue.toTuple(IValue.java:313)
```

if anyone solve this error please help us

**Comment by aravinthk00** [comment]
Please try that below lines , It's work for me.

final Tensor inputTensor = TensorImageUtils.bitmapToFloat32Tensor(resizedBitmap, PrePostProcessor.NO_MEAN_RGB, PrePostProcessor.NO_STD_RGB);
        IValue[] outputTuple = mModule.forward(IValue.from(inputTensor)).toTuple();
        final Tensor outputTensor = outputTuple[0].toTensor();
        final float[] outputs = outputTensor.getDataAsFloatArray();

Thanks..
