### ISSUE TITLE
Error in Custom model, How do train and export the custom model suitable for Object Detection Pytorch App ?

### ISSUE THREAD

**Issue by aravinthk00** [pytorch/android-demo-app#277]
Please give me brief detail about How do train the custom model for Object Detection Pytorch App & HelloWorld App ?

**Comment by aravinthk00** [comment]
if I load the custom model in Object Detection APP, I am facing issues , my logcast 👍 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 8597
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: Lite Interpreter version number does not match. The model version must be between 3 and 7 but the model version is 8 ()
    Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:317 (most recent call first):
    (no backtrace available)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: com.facebook.jni.CppException: Lite Interpreter version number does not match. The model version must be between 3 and 7 but the model version is 8 ()
    Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:317 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.initHybrid(Native Method)
        at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:28)
        at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:30)
        at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:184)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8269)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
        	... 12 more

Already I read and try that repo issue given solutions, But I can't get solution .. please help me out ... Advanced in thanks...

**Comment by aravinthk00** [comment]
**I follow this [ android-demo-app](https://github.com/pytorch/android-demo-app)/ObjectDetection/ ](https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection) ] steps only, after the export , I get best.torchscript.ptl  but import in android app facing issue on model version above mentioned, then model version issue resolve refer that [ https://github.com/pytorch/android-demo-app/issues ], now I am struggling in error like below** 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 4679
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: isTuple()INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue_inl.h":1396, please report a bug to PyTorch. Expected Tuple but got String ()
    Exception raised from toTuple at ../aten/src/ATen/core/ivalue_inl.h:1396 (most recent call first):
    (no backtrace available)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: com.facebook.jni.CppException: isTuple()INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue_inl.h":1396, please report a bug to PyTorch. Expected Tuple but got String ()
    Exception raised from toTuple at ../aten/src/ATen/core/ivalue_inl.h:1396 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.initHybrid(Native Method)
        at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:28)
        at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:30)
        at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:184)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8269)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
        	... 12 more

 I can't get idea about that, please give me solution ... anyone assist me..

**Comment by aravinthk00** [comment]
I fix this issue, just I upadate on
 " implementation 'org.pytorch:pytorch_android_lite:1.12.1'
    implementation 'org.pytorch:pytorch_android_torchvision_lite:1.10.0'
 in my build.gradle file. it's work for me . you also check once, It will helps for others. 

Thankyou :-)

**Comment by dkdk12** [comment]
@aravinthk00 need some help regarding this repository. can you provide me your email address?
