### ISSUE TITLE
Custom model doesn't work

### ISSUE THREAD

**Issue by antonlebedjko** [pytorch/android-demo-app#28]
Hi! I used a pre trained resnet 18 model and have run it on my dataset, after that I have saved it as it was described in tutorial (https://heartbeat.fritz.ai/pytorch-mobile-image-classification-on-android-5c0cfb774c5b). I have torch version 1.3.0, which is correct. My programme works correctly with the model from a tutorial as well, but when I am running my custom one, I get this error message:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.carclassificator, PID: 13187
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.carclassificator/com.example.carclassificator.CarImageActivity}: com.facebook.jni.CppException: false CHECK FAILED at ../c10/core/Backend.h (tensorTypeIdToBackend at ../c10/core/Backend.h:106)
    (no backtrace available)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.access$1000(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: com.facebook.jni.CppException: false CHECK FAILED at ../c10/core/Backend.h (tensorTypeIdToBackend at ../c10/core/Backend.h:106)
    (no backtrace available)
        at org.pytorch.Module$NativePeer.initHybrid(Native Method)
        at org.pytorch.Module$NativePeer.<init>(Module.java:70)
        at org.pytorch.Module.<init>(Module.java:25)
        at org.pytorch.Module.load(Module.java:21)
        at com.example.carclassificator.Classifier.<init>(Classifier.java:18)
        at com.example.carclassificator.CarImageActivity.onCreate(CarImageActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:6609)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        	... 10 more`

Can you help me, please?

**Comment by antonlebedjko** [comment]
I actually found out the issue myself, forgot to call model.eval(). Maybe will be useful for someone else
