### ISSUE TITLE
When I load my model, I get an error

### ISSUE THREAD

**Issue by ultracxx1997** [pytorch/android-demo-app#42]
```
public void test(View view) {
        Module module = null;
        Log.i("test", "test: load pt fail!");
        try {
            // creating bitmap from packaged into app android asset 'image.jpg',
            // app/src/main/assets/image.jpg
            // loading serialized torchscript module from packaged into app android asset model.pt,
            // app/src/model/assets/model.pt
            String str = assetFilePath(this, "urban.pt");
            module = Module.load(str);
        } catch (Exception e) {
            Log.e("PytorchHelloWorld", "Error reading assets", e);
            finish();
        }
        Log.i("test", "test: load pt success!");
        Toast.makeText(MainActivity.this,"测试按钮3",Toast.LENGTH_SHORT).show();
    }
```

when program run on 
`module = Module.load(str);`

a exception will be caught

```
2019-12-06 16:07:47.811 6636-6636/com.example.activitytest E/PytorchHelloWorld: Error reading assets
    com.facebook.jni.CppException: [enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory
    (no backtrace available)
        at org.pytorch.Module$NativePeer.initHybrid(Native Method)
        at org.pytorch.Module$NativePeer.<init>(Module.java:70)
        at org.pytorch.Module.<init>(Module.java:25)
        at org.pytorch.Module.load(Module.java:21)
        at com.example.activitytest.MainActivity.test(MainActivity.java:50)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

i have no idea about this question

could you help me?

**Comment by ultracxx1997** [comment]
this is the model code!!
```
class VGGish(nn.Module):

    def __init__(self):

        super(VGGish, self).__init__()

        self.n_bins = 64
        self.n_frames = 96
        self.out_dims = int(64 / 2 ** 4 * 96 / 2 ** 4)
        self.n_classes = 2
        self.weights = 'vggish_audioset_weights_without_fc2.h5'
        self.model_zoo = 'models'
        self.name = 'bird'

        # convolutional bottom part
        self.conv1 = nn.Conv2d(1, 64, kernel_size=(3, 3), padding=(1, 1))
        self.pool1 = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv2 = nn.Conv2d(64, 128, kernel_size=(3, 3), padding=(1, 1))
        self.pool2 = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv3_1 = nn.Conv2d(128, 256, kernel_size=(3, 3), padding=(1, 1))
        self.conv3_2 = nn.Conv2d(256, 256, kernel_size=(3, 3), padding=(1, 1))
        self.pool3 = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv4_1 = nn.Conv2d(256, 512, kernel_size=(3, 3), padding=(1, 1))
        self.conv4_2 = nn.Conv2d(512, 512, kernel_size=(3, 3), padding=(1, 1))
        self.pool4 = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))

        # fully connected top part
        self.classifier = nn.Sequential(
            nn.Linear(self.out_dims * 512, 1028),
            nn.ReLU(),
            nn.Linear(1028, 1028),
            nn.ReLU(),
            nn.Linear(1028, self.n_classes)
        )

    def forward(self, X):

        a = self.pool1(relu(self.conv1(X)))
        a = self.pool2(relu(self.conv2(a)))
        a = relu(self.conv3_1(a))
        a = relu(self.conv3_2(a))
        a = self.pool3(a)
        a = relu(self.conv4_1(a))
        a = relu(self.conv4_2(a))
        a = self.pool4(a)
        a = a.reshape((a.size(0), -1))
        a = self.classifier(a)
        a = softmax(a)
        return a

    def init_weights(self, file=None):
        '''
        laods pretrained weights from an .hdf5 file. File structure must match exactly.

        Args:
            file (string): path to .hdf5 file containing VGGish weights
        '''

        if file is not None:
            file = file
        else:
            file = self.weights

        # loading weights from file
        with h5.File(file, 'r') as f:

            conv1 = f['conv1']['conv1']
            kernels1 = torch.from_numpy(conv1['kernel:0'][()].transpose(3, 2, 1, 0))
            biases1 = torch.from_numpy(conv1['bias:0'][()])
            conv2 = f['conv2']['conv2']
            kernels2 = torch.from_numpy(conv2['kernel:0'][()].transpose(3, 2, 1, 0))
            biases2 = torch.from_numpy(conv2['bias:0'][()])
            conv3_1 = f['conv3']['conv3_1']['conv3']['conv3_1']
            kernels3_1 = torch.from_numpy(conv3_1['kernel:0'][()].transpose(3, 2, 1, 0))
            biases3_1 = torch.from_numpy(conv3_1['bias:0'][()])
            conv3_2 = f['conv3']['conv3_2']['conv3']['conv3_2']
            kernels3_2 = torch.from_numpy(conv3_2['kernel:0'][()].transpose(3, 2, 1, 0))
            biases3_2 = torch.from_numpy(conv3_2['bias:0'][()])
            conv4_1 = f['conv4']['conv4_1']['conv4']['conv4_1']
            kernels4_1 = torch.from_numpy(conv4_1['kernel:0'][()].transpose(3, 2, 1, 0))
            biases4_1 = torch.from_numpy(conv4_1['bias:0'][()])
            conv4_2 = f['conv4']['conv4_2']['conv4']['conv4_2']
            kernels4_2 = torch.from_numpy(conv4_2['kernel:0'][()].transpose(3, 2, 1, 0))
            biases4_2 = torch.from_numpy(conv4_2['bias:0'][()])

            # assigning weights to layers
            self.conv1.weight.data = kernels1
            self.conv1.bias.data = biases1
            self.conv2.weight.data = kernels2
            self.conv2.bias.data = biases2
            self.conv3_1.weight.data = kernels3_1
            self.conv3_1.bias.data = biases3_1
            self.conv3_2.weight.data = kernels3_2
            self.conv3_2.bias.data = biases3_2
            self.conv4_1.weight.data = kernels4_1
            self.conv4_1.bias.data = biases4_1
            self.conv4_2.weight.data = kernels4_2
            self.conv4_2.bias.data = biases4_2

    def freeze_bottom(self):
        '''
        freezes the convolutional bottom part of the model.
        '''
        for layer in self.children():
            if isinstance(layer, nn.Conv2d):
                layer.weight.requires_grad = False
                layer.bias.requires_grad = False

    def save_weights(self):
        torch.save(self.state_dict(), \
                   os.path.join(self.model_zoo, self.name + '.pt'))
        return



```

**Comment by dreiss** [comment]
It sounds like `urban.pt` is not a valid zip file.  Can you run `adb pull` to retrieve it from the device, then run zipinfo on it?

**Comment by ultracxx1997** [comment]
thanks, i just found my `urban.pt` is only file of weight,it's not a complete model,i'm so stupid

**Comment by ultracxx1997** [comment]
> It sounds like `urban.pt` is not a valid zip file. Can you run `adb pull` to retrieve it from the device, then run zipinfo on it?

```
Archive:  net.pt
[net.pt]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  net.pt may be a plain executable, not an archive
zipinfo:  cannot find zipfile directory in one of net.pt or
          net.pt.zip, and cannot find net.pt.ZIP, period.

```
`urban.pt` is not a zip file.  just made by  `torch.save(model,'urban.pt')`
is something wrong?

**Comment by IvanKobzarev** [comment]
@ultracxx1997 
> `urban.pt` is not a zip file. just made by `torch.save(model,'urban.pt')`
> is something wrong?

Essentially pt format files are zip archives. 
If it is not valid zip - probably there might be some file collisions, like appending new zip archive content existing zip file etc.

And we need to call `model.eval()` before tracing
```
resnet18 = torchvision.models.resnet18(pretrained=True)
resnet18.eval()
resnet18_traced = torch.jit.trace(resnet18, torch.rand(1, 3, 224, 224)).save("app/src/main/assets/resnet18.pt")
```

**Comment by ultracxx1997** [comment]
> @ultracxx1997
> 
> > `urban.pt` is not a zip file. just made by `torch.save(model,'urban.pt')`
> > is something wrong?
> 
> Essentially pt format files are zip archives.
> If it is not valid zip - probably there might be some file collisions, like appending new zip archive content existing zip file etc.
> 
> And we need to call `model.eval()` before tracing
> 
> ```
> resnet18 = torchvision.models.resnet18(pretrained=True)
> resnet18.eval()
> resnet18_traced = torch.jit.trace(resnet18, torch.rand(1, 3, 224, 224)).save("app/src/main/assets/resnet18.pt")
> ```

太感谢你了！
thank you very much！

**Comment by shirattias** [comment]
Hi, Did you solve tthe problem?
I'm facing the same one
