### ISSUE TITLE
Problem with YOLO .pt model

### ISSUE THREAD

**Issue by kamil11145** [pytorch/android-demo-app#52]
I have a problem with run model YOLO implemented in Pytorch. I used a few repositories e.g:
https://github.com/eriklindernoren/PyTorch-YOLOv3
https://github.com/ayooshkathuria/pytorch-yolo-v3

To save YOLO model in .pt I add to detect.py (in both project) below lines after "model.eval()":
model.eval()
example = get_test_input()   #return common image (size 416x416 which is equal to input size)
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save("./yolov3_model.pt")

Model saved correctly with below warnings:
C:\(...)\models.py:204: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if grid_size != self.grid_size:
C:\(...)\models.py:208: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  pred_boxes = FloatTensor(prediction[..., :4].shape)

When I copy this saved model to assets and trying to run HelloWorld/Demo App I got error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.helloworld, PID: 20315
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.helloworld/org.pytorch.helloworld.MainActivity}: com.facebook.jni.CppException: empty_strided not implemented for TensorTypeSet(VariableTensorId, CUDATensorId) (empty_strided at aten/src/ATen/Functions.h:3771)
    (no backtrace available)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5631)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: com.facebook.jni.CppException: empty_strided not implemented for TensorTypeSet(VariableTensorId, CUDATensorId) (empty_strided at aten/src/ATen/Functions.h:3771)
    (no backtrace available)
        at org.pytorch.NativePeer.initHybrid(Native Method)
        at org.pytorch.NativePeer.<init>(NativePeer.java:20)
        at org.pytorch.Module.load(Module.java:23)
        at org.pytorch.helloworld.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        	... 10 more

I can add that I was trying to save this model with and without CUDA (using set CUDA_VISIBLE_DEVICES=-1)

Moreover I change in project (in other case it resolve problem):
    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'

I also tried with other custom models (models from torch vision working well-I tried a few) and get similar result. Is anyone who can say what is wrong or how to save model to work correctly in this demo app?

**Comment by kamil11145** [comment]
The problem has been solved thanks to the latest changes (I download the latest repository once again and problem disappeared). Second case was to prepare YOLO model to return percentage.
That's all. I'm closing this issue.

**Comment by padmasreenagarajan** [comment]
Even i faced the same error.Could u please share the link for new repository?
@kamil11145

**Comment by kamil11145** [comment]
Hi @padmasreenagarajan!
I got this error when I used this repository in version: "[cleanup] Remove unused model from assets" (Commits on Oct 11, 2019). Later I download THE SAME repository (but newest version) [version_bump] 1.4.0 and this error disappeared.

**Comment by padmasreenagarajan** [comment]
is there any other way to resolve this issue in Python itself?
Do help me out please.
