### ISSUE TITLE
change a model ,  produce a bug when run Module.load(path)

### ISSUE THREAD

**Issue by AR-fan** [pytorch/android-demo-app#90]
Hi, I use the PyTorchDemoApp, and just change a model(model.pt), then produce a bug:  

[model.zip](https://github.com/pytorch/android-demo-app/files/5516928/model.zip)
[SINet.zip](https://github.com/pytorch/android-demo-app/files/5516936/SINet.zip)

there is bug info:  
```  
2020-11-10 19:26:55.384 24242-24242/? E/rg.pytorch.dem: Unknown bits set in runtime_flags: 0x8000
2020-11-10 19:26:55.551 24242-24278/org.pytorch.demo E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@fbc96a3
2020-11-10 19:26:59.404 24242-24366/org.pytorch.demo E/ion: ioctl c0044901 failed with code -1: Not a typewriter
2020-11-10 19:26:59.489 24242-24312/org.pytorch.demo E/PyTorchDemo: Error during image analysis
    com.facebook.jni.CppException: 
    
    aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
    Expected at most 12 arguments but found 13 positional arguments.
    :
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py(420): _conv_forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py(423): forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(709): _slow_forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(725): _call_impl
    <ipython-input-1-c7e8f5a12ccb>(50): forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(709): _slow_forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(725): _call_impl
    <ipython-input-1-c7e8f5a12ccb>(482): forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(709): _slow_forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(725): _call_impl
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py(117): forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(709): _slow_forward
    /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(725): _call_impl
    /usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py(940): trace_module
    /usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py(742): trace
    <ipython-input-2-73e23819fe7f>(25): <module>
    /usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2882): run_code
    /usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2822): run_ast_nodes
    /usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2718): run_cell
    /usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py(537): run_cell
    /usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py(208): do_execute
    /usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(399): execute_request
    /usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(233): dispatch_shell
    /usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(283): dispatcher
    /usr/local/lib/python3.6/dist-packages/tornado/stack_context.py(300): null_wrapper
    /usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(444): _run_callback
    /usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(492): _handle_recv
    /usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(462): _handle_events
    /usr/local/lib/python3.6/dist-packages/tornado/stack_context.py(300): null_wrapper
    /usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py(122): _handle_events
    /usr/lib/python3.6/asyncio/events.py(145): _run
    /usr/lib/python3.6/asyncio/base_events.py(1451): _run_once
    /usr/lib/python3.6/asyncio/base_events.py(438): run_forever
    /usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py(132): start
    /usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py(499): start
    /usr/local/lib/python3.6/dist-packages/traitlets/config/application.py(664): launch_instance
    /usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py(16): <module>
    /usr/lib/python3.6/runpy.py(85): _run_code
    /usr/lib/python3.6/runpy.py(193): _run_module_as_main
    Serialized   File "code/__torch__/torch/nn/modules/conv.py", line 8
      def forward(self: __torch__.torch.nn.modules.conv.Conv2d,
        input: Tensor) -> Tensor:
        input0 = torch._convolution(input, self.weight, None, [2, 2], [1, 1], [1, 1], False, [0, 0], 1, False, False, True, True)
                 ~~~~~~~~~~~~~~~~~~ <--- HERE
        return input0
    
        at org.pytorch.NativePeer.initHybrid(Native Method)
        at org.pytorch.NativePeer.<init>(NativePeer.java:24)
        at org.pytorch.Module.load(Module.java:23)
        at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:167)
2020-11-10 19:26:59.489 24242-24312/org.pytorch.demo E/PyTorchDemo:     at org.pytorch.demo.vision.ImageClassificationActivity.analyzeImage(ImageClassificationActivity.java:31)
        at org.pytorch.demo.vision.AbstractCameraXActivity.lambda$setupCameraX$2$AbstractCameraXActivity(AbstractCameraXActivity.java:90)
        at org.pytorch.demo.vision.-$$Lambda$AbstractCameraXActivity$t0OjLr-l_M0-_0_dUqVE4yqEYnE.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:57)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:135)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by xiaozhaozhaomhz** [comment]
I have the same questions

**Comment by xiaozhaozhaomhz** [comment]
did you fix it

**Comment by AR-fan** [comment]
no, I give up,  I am using tflite, maybe you can try ncnn and so on.

**Comment by DanielSawczuk** [comment]
I had similar issue. Changing pytorch version (in build.gradle) to 1.7 resolved the problem:

```
implementation 'org.pytorch:pytorch_android:1.7.0'
implementation 'org.pytorch:pytorch_android_torchvision:1.7.0'
````

**Comment by DUTxutengfei** [comment]
> 
> 
> I had similar issue. Changing pytorch version (in build.gradle) to 1.7 resolved the problem:
> 
> ```
> implementation 'org.pytorch:pytorch_android:1.7.0'
> implementation 'org.pytorch:pytorch_android_torchvision:1.7.0'
> ```

the problem is solved,thx!

**Comment by AR-fan** [comment]
cool

**Comment by hjbhjbhjb** [comment]
> cool

I get the same question in jetson xavier nx when I deploy model ,can you help me fix it?

**Comment by hjbhjbhjb** [comment]
> I had similar issue. Changing pytorch version (in build.gradle) to 1.7 resolved the problem:
> 
> ```
> implementation 'org.pytorch:pytorch_android:1.7.0'
> implementation 'org.pytorch:pytorch_android_torchvision:1.7.0'
> ```

I get the same question in jetson xavier nx when I deploy model ,can you help me fix it?

**Comment by PQ-girl** [comment]
你好，我导入pytorch包的时候没有错误，但显示错误，只能导入pytorch1.1，这是什么原因造成的

**Comment by hjbhjbhjb** [comment]
你先检查什么错误&nbsp; 我当时是因为torch版本不对应&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, May 17, 2022 16:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pytorch/android-demo-app] change a model ,  produce a bug whenrun Module.load(path) (#90)




 
你好，我导入pytorch包的时候没有错误，但显示错误，只能导入pytorch1.1，这是什么原因造成的

**Comment by PQ-girl** [comment]
没有错误，最后只是显示Failed to resolve: :org.pytorch:pytorch_android:1.3.0，没有标红，标黄了，应该是警告，这是什么原因呢

**Comment by hjbhjbhjb** [comment]
不好意思&nbsp; 我没有遇到过&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, May 17, 2022 17:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pytorch/android-demo-app] change a model ,  produce a bug whenrun Module.load(path) (#90)




 
没有错误，最后只是显示Failed to resolve: :org.pytorch:pytorch_android:1.3.0，没有标红，标黄了，应该是警告，这是什么原因呢
